spring:
  application:
    name: store-gateway

  cloud:
    discovery:
      locator:
        enabled: true
    gateway:
      routes:
        - id: store-auth
          uri: lb://store-auth
          predicates:
            - Path=/auth/**

        - id: store-account
          uri: lb://store-account
          predicates:
            - Path=/accounts/**

        - id: insper
          uri: https://www.insper.edu.br
          predicates:
            - Path=/

        - id: store-product
          uri: lb://store-product
          predicates:
            - Path=/products/**

        - id: store-order
          uri: lb://store-order
          predicates:
            - Path=/orders/**

management:
  endpoints:
    web:
      base-path: /gateway/actuator
      exposure:
        iinclude: ['*', 'prometheus']

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${DISCOVERY_HOST}:8761/eureka/
  
api:
  endpoints:
    open: >
      POST /auth/register,
      POST /auth/login,
      ANY /auth/actuator,
      ANY /accounts/actuator,
      ANY /products/actuator,
      ANY /orders/actuator,
      ANY /gateway/actuator,
      ANY /auth/swagger**,
      ANY /accounts/swagger**,
      ANY /products/swagger**,
      ANY /orders/swagger**,
      ANY /auth/v3**,
      ANY /accounts/v3**,
      ANY /products/v3**,
      ANY /orders/v3**

springdoc:
  swagger-ui:
    enabled: true
    url: /v3/api-docs
  api-docs:
    enabled: true